// Copyright (C) Parity Technologies (UK) Ltd.
// This file is part of Cumulus.

// Cumulus is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// Cumulus is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with Cumulus.  If not, see <http://www.gnu.org/licenses/>.

//! Autogenerated weights for pallet_ambassador_governance
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2025-08-11, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `localhost`, CPU: `Apple M1 Pro`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("collectives-polkadot-dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/polkadot-parachain
// benchmark
// pallet
// --chain=collectives-polkadot-dev
// --steps=50
// --repeat=20
// --pallet=pallet_ambassador_governance
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --heap-pages=4096
// --output=./runtime/collectives/collectives-polkadot/src/weights/pallet_ambassador_governance.rs
// --template=./.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions for `pallet_ambassador_governance`.
pub struct WeightInfo<T>(PhantomData<T>);

impl<T: frame_system::Config> pallet_ambassador_governance::WeightInfo for WeightInfo<T> {
    // Storage: AmbassadorGovernance Emergencies (r:1 w:1)
    // Storage: AmbassadorGovernance EmergencyCount (r:1 w:1)
    fn activate_emergency_protocol() -> Weight {
        Weight::from_parts(25_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(2))
    }
    
    // Storage: AmbassadorGovernance Emergencies (r:1 w:1)
    // Storage: AmbassadorGovernance EmergencyCommittees (r:1 w:1)
    fn form_emergency_committee() -> Weight {
        Weight::from_parts(30_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(2))
    }
    
    // Storage: AmbassadorGovernance Emergencies (r:1 w:1)
    fn resolve_emergency() -> Weight {
        Weight::from_parts(25_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    
    // Storage: AmbassadorGovernance Appeals (r:1 w:1)
    // Storage: AmbassadorGovernance AppealCount (r:1 w:1)
    fn submit_appeal() -> Weight {
        Weight::from_parts(25_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(2))
    }
    
    // Storage: AmbassadorGovernance Appeals (r:1 w:1)
    // Storage: AmbassadorGovernance AppealCommittees (r:1 w:1)
    fn form_appeal_committee() -> Weight {
        Weight::from_parts(30_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(2))
    }
    
    // Storage: AmbassadorGovernance Appeals (r:1 w:1)
    fn decide_appeal() -> Weight {
        Weight::from_parts(25_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    
    // Storage: AmbassadorGovernance Integrations (r:1 w:1)
    // Storage: AmbassadorGovernance IntegrationCount (r:1 w:1)
    fn establish_integration() -> Weight {
        Weight::from_parts(25_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(2))
    }
    
    // Storage: AmbassadorGovernance DisciplinaryActions (r:1 w:1)
    // Storage: AmbassadorGovernance DisciplinaryActionCount (r:1 w:1)
    fn initiate_disciplinary_action() -> Weight {
        Weight::from_parts(25_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(2))
    }
    
    // Storage: AmbassadorGovernance RankTransitions (r:1 w:1)
    // Storage: AmbassadorGovernance RankTransitionCount (r:1 w:1)
    fn initiate_rank_transition() -> Weight {
        Weight::from_parts(25_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(2))
    }
    
    // Storage: AmbassadorGovernance ConflictsOfInterest (r:1 w:1)
    // Storage: AmbassadorGovernance ConflictOfInterestCount (r:1 w:1)
    fn register_conflict_of_interest() -> Weight {
        Weight::from_parts(25_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(2))
    }
    
    // Storage: AmbassadorGovernance Remarks (r:1 w:1)
    // Storage: AmbassadorGovernance RemarkCount (r:1 w:1)
    fn create_remark() -> Weight {
        Weight::from_parts(20_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(2))
    }
    
    // Storage: AmbassadorGovernance HealthMetrics (r:1 w:1)
    fn update_governance_health_metrics() -> Weight {
        Weight::from_parts(15_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    
    // Storage: AmbassadorGovernance ServiceProviders (r:1 w:1)
    // Storage: AmbassadorGovernance ServiceProviderCount (r:1 w:1)
    fn register_service_provider() -> Weight {
        Weight::from_parts(25_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(2))
    }
    
    // Storage: AmbassadorGovernance ServiceReferrals (r:1 w:1)
    // Storage: AmbassadorGovernance ServiceReferralCount (r:1 w:1)
    fn create_service_referral() -> Weight {
        Weight::from_parts(25_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(2))
    }
}
