// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_ambassador_governance`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 50.0.0
//! DATE: 2025-08-12, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `lss-MacBook-Pro.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// ./target/release/wbuild/collectives-polkadot-runtime/collectives_polkadot_runtime.wasm
// --pallet
// pallet_ambassador_governance
// --extrinsic
// *
// --template
// ./frame-weight-template.hbs
// --output
// ./pallets/ambassador-governance/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_ambassador_governance`.
pub trait WeightInfo {
	fn activate_emergency_protocol() -> Weight;
	fn form_emergency_committee() -> Weight;
	fn resolve_emergency() -> Weight;
	fn submit_appeal() -> Weight;
	fn form_appeal_committee() -> Weight;
	fn decide_appeal() -> Weight;
	fn establish_integration() -> Weight;
	fn register_service_provider() -> Weight;
	fn create_service_referral() -> Weight;
	fn initiate_disciplinary_action() -> Weight;
	fn initiate_rank_transition() -> Weight;
	fn register_conflict_of_interest() -> Weight;
	fn create_remark() -> Weight;
	fn update_governance_health_metrics() -> Weight;
}

/// Weights for `pallet_ambassador_governance` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `AmbassadorGovernance::Emergencies` (r:0 w:1)
	/// Proof: `AmbassadorGovernance::Emergencies` (`max_values`: None, `max_size`: Some(10127), added: 12602, mode: `MaxEncodedLen`)
	fn activate_emergency_protocol() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_000_000 picoseconds.
		Weight::from_parts(6_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `AmbassadorGovernance::EmergencyCommittees` (r:0 w:1)
	/// Proof: `AmbassadorGovernance::EmergencyCommittees` (`max_values`: None, `max_size`: Some(379), added: 2854, mode: `MaxEncodedLen`)
	fn form_emergency_committee() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_000_000 picoseconds.
		Weight::from_parts(6_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `AmbassadorGovernance::Emergencies` (r:1 w:1)
	/// Proof: `AmbassadorGovernance::Emergencies` (`max_values`: None, `max_size`: Some(10127), added: 12602, mode: `MaxEncodedLen`)
	fn resolve_emergency() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `339`
		//  Estimated: `13592`
		// Minimum execution time: 11_000_000 picoseconds.
		Weight::from_parts(12_000_000, 13592)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `AmbassadorGovernance::Appeals` (r:0 w:1)
	/// Proof: `AmbassadorGovernance::Appeals` (`max_values`: None, `max_size`: Some(20129), added: 22604, mode: `MaxEncodedLen`)
	fn submit_appeal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_000_000 picoseconds.
		Weight::from_parts(6_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `AmbassadorGovernance::Appeals` (r:1 w:1)
	/// Proof: `AmbassadorGovernance::Appeals` (`max_values`: None, `max_size`: Some(20129), added: 22604, mode: `MaxEncodedLen`)
	/// Storage: `AmbassadorGovernance::AppealCommittees` (r:0 w:1)
	/// Proof: `AmbassadorGovernance::AppealCommittees` (`max_values`: None, `max_size`: Some(369), added: 2844, mode: `MaxEncodedLen`)
	fn form_appeal_committee() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `327`
		//  Estimated: `23594`
		// Minimum execution time: 12_000_000 picoseconds.
		Weight::from_parts(13_000_000, 23594)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `AmbassadorGovernance::Appeals` (r:1 w:1)
	/// Proof: `AmbassadorGovernance::Appeals` (`max_values`: None, `max_size`: Some(20129), added: 22604, mode: `MaxEncodedLen`)
	fn decide_appeal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `376`
		//  Estimated: `23594`
		// Minimum execution time: 11_000_000 picoseconds.
		Weight::from_parts(12_000_000, 23594)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `AmbassadorGovernance::Integrations` (r:0 w:1)
	/// Proof: `AmbassadorGovernance::Integrations` (`max_values`: None, `max_size`: Some(11404), added: 13879, mode: `MaxEncodedLen`)
	fn establish_integration() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_000_000 picoseconds.
		Weight::from_parts(6_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `AmbassadorGovernance::ServiceProviders` (r:0 w:1)
	/// Proof: `AmbassadorGovernance::ServiceProviders` (`max_values`: None, `max_size`: Some(20131), added: 22606, mode: `MaxEncodedLen`)
	fn register_service_provider() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_000_000 picoseconds.
		Weight::from_parts(6_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `AmbassadorGovernance::ServiceReferrals` (r:0 w:1)
	/// Proof: `AmbassadorGovernance::ServiceReferrals` (`max_values`: None, `max_size`: Some(30093), added: 32568, mode: `MaxEncodedLen`)
	fn create_service_referral() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_000_000 picoseconds.
		Weight::from_parts(6_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	fn initiate_disciplinary_action() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_000_000 picoseconds.
		Weight::from_parts(4_000_000, 0)
	}
	fn initiate_rank_transition() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_000_000 picoseconds.
		Weight::from_parts(4_000_000, 0)
	}
	/// Storage: `AmbassadorGovernance::Conflicts` (r:0 w:1)
	/// Proof: `AmbassadorGovernance::Conflicts` (`max_values`: None, `max_size`: Some(20095), added: 22570, mode: `MaxEncodedLen`)
	fn register_conflict_of_interest() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(10_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `AmbassadorGovernance::Remarks` (r:0 w:1)
	/// Proof: `AmbassadorGovernance::Remarks` (`max_values`: None, `max_size`: Some(20122), added: 22597, mode: `MaxEncodedLen`)
	fn create_remark() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 10_000_000 picoseconds.
		Weight::from_parts(11_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `AmbassadorGovernance::GovernanceHealth` (r:0 w:1)
	/// Proof: `AmbassadorGovernance::GovernanceHealth` (`max_values`: Some(1), `max_size`: Some(10), added: 505, mode: `MaxEncodedLen`)
	fn update_governance_health_metrics() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_000_000 picoseconds.
		Weight::from_parts(4_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `AmbassadorGovernance::Emergencies` (r:0 w:1)
	/// Proof: `AmbassadorGovernance::Emergencies` (`max_values`: None, `max_size`: Some(10127), added: 12602, mode: `MaxEncodedLen`)
	fn activate_emergency_protocol() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_000_000 picoseconds.
		Weight::from_parts(6_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `AmbassadorGovernance::EmergencyCommittees` (r:0 w:1)
	/// Proof: `AmbassadorGovernance::EmergencyCommittees` (`max_values`: None, `max_size`: Some(379), added: 2854, mode: `MaxEncodedLen`)
	fn form_emergency_committee() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_000_000 picoseconds.
		Weight::from_parts(6_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `AmbassadorGovernance::Emergencies` (r:1 w:1)
	/// Proof: `AmbassadorGovernance::Emergencies` (`max_values`: None, `max_size`: Some(10127), added: 12602, mode: `MaxEncodedLen`)
	fn resolve_emergency() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `339`
		//  Estimated: `13592`
		// Minimum execution time: 11_000_000 picoseconds.
		Weight::from_parts(12_000_000, 13592)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `AmbassadorGovernance::Appeals` (r:0 w:1)
	/// Proof: `AmbassadorGovernance::Appeals` (`max_values`: None, `max_size`: Some(20129), added: 22604, mode: `MaxEncodedLen`)
	fn submit_appeal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_000_000 picoseconds.
		Weight::from_parts(6_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `AmbassadorGovernance::Appeals` (r:1 w:1)
	/// Proof: `AmbassadorGovernance::Appeals` (`max_values`: None, `max_size`: Some(20129), added: 22604, mode: `MaxEncodedLen`)
	/// Storage: `AmbassadorGovernance::AppealCommittees` (r:0 w:1)
	/// Proof: `AmbassadorGovernance::AppealCommittees` (`max_values`: None, `max_size`: Some(369), added: 2844, mode: `MaxEncodedLen`)
	fn form_appeal_committee() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `327`
		//  Estimated: `23594`
		// Minimum execution time: 12_000_000 picoseconds.
		Weight::from_parts(13_000_000, 23594)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `AmbassadorGovernance::Appeals` (r:1 w:1)
	/// Proof: `AmbassadorGovernance::Appeals` (`max_values`: None, `max_size`: Some(20129), added: 22604, mode: `MaxEncodedLen`)
	fn decide_appeal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `376`
		//  Estimated: `23594`
		// Minimum execution time: 11_000_000 picoseconds.
		Weight::from_parts(12_000_000, 23594)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `AmbassadorGovernance::Integrations` (r:0 w:1)
	/// Proof: `AmbassadorGovernance::Integrations` (`max_values`: None, `max_size`: Some(11404), added: 13879, mode: `MaxEncodedLen`)
	fn establish_integration() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_000_000 picoseconds.
		Weight::from_parts(6_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `AmbassadorGovernance::ServiceProviders` (r:0 w:1)
	/// Proof: `AmbassadorGovernance::ServiceProviders` (`max_values`: None, `max_size`: Some(20131), added: 22606, mode: `MaxEncodedLen`)
	fn register_service_provider() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_000_000 picoseconds.
		Weight::from_parts(6_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `AmbassadorGovernance::ServiceReferrals` (r:0 w:1)
	/// Proof: `AmbassadorGovernance::ServiceReferrals` (`max_values`: None, `max_size`: Some(30093), added: 32568, mode: `MaxEncodedLen`)
	fn create_service_referral() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_000_000 picoseconds.
		Weight::from_parts(6_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	fn initiate_disciplinary_action() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_000_000 picoseconds.
		Weight::from_parts(4_000_000, 0)
	}
	fn initiate_rank_transition() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_000_000 picoseconds.
		Weight::from_parts(4_000_000, 0)
	}
	/// Storage: `AmbassadorGovernance::Conflicts` (r:0 w:1)
	/// Proof: `AmbassadorGovernance::Conflicts` (`max_values`: None, `max_size`: Some(20095), added: 22570, mode: `MaxEncodedLen`)
	fn register_conflict_of_interest() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(10_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `AmbassadorGovernance::Remarks` (r:0 w:1)
	/// Proof: `AmbassadorGovernance::Remarks` (`max_values`: None, `max_size`: Some(20122), added: 22597, mode: `MaxEncodedLen`)
	fn create_remark() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 10_000_000 picoseconds.
		Weight::from_parts(11_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `AmbassadorGovernance::GovernanceHealth` (r:0 w:1)
	/// Proof: `AmbassadorGovernance::GovernanceHealth` (`max_values`: Some(1), `max_size`: Some(10), added: 505, mode: `MaxEncodedLen`)
	fn update_governance_health_metrics() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_000_000 picoseconds.
		Weight::from_parts(4_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
